---
dist: xenial
sudo: required

language: python
python: "3.6"

services:
  - docker

branches:
  only:
    - master

before_install:
  - docker pull williamyeh/ansible:ubuntu16.04
  - docker pull williamyeh/ansible:ubuntu14.04

script:
  - make test

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
